FROM python:3.10-slim

WORKDIR /app

# Copia el script y el Excel
COPY 7.0_rl/scripts/generate_inventory_data.py .
COPY 7.0_rl/scripts/data/online_retail.xlsx ./data/online_retail.xlsx

# Instala dependencias
RUN pip install pandas cassandra-driver openpyxl

CMD ["python", "generate_inventory_data.py"] 