# Basic cluster configuration
cluster_name: 'EcommerceCluster'
num_tokens: 16
hinted_handoff_enabled: true
max_hint_window_in_ms: 10800000 # 3 hours
hinted_handoff_throttle_in_kb: 1024

# Authentication and authorization
authenticator: AllowAllAuthenticator
authorizer: AllowAllAuthorizer

# Network settings
listen_address: cassandra
broadcast_address: cassandra
rpc_address: 0.0.0.0
broadcast_rpc_address: cassandra

# Native protocol
start_native_transport: true
native_transport_port: 9042
native_transport_max_threads: 128
native_transport_max_frame_size_in_mb: 256

# Storage settings
data_file_directories:
  - /var/lib/cassandra/data
commitlog_directory: /var/lib/cassandra/commitlog
saved_caches_directory: /var/lib/cassandra/saved_caches

# Performance settings
commitlog_sync: periodic
commitlog_sync_period_in_ms: 10000
commitlog_segment_size_in_mb: 32

# Compaction settings
compaction_throughput_mb_per_sec: 16
concurrent_compactors: 1

# Memory settings
memtable_allocation_type: heap_buffers
concurrent_reads: 32
concurrent_writes: 32
concurrent_counter_writes: 32

# Cache settings
row_cache_size_in_mb: 0
key_cache_size_in_mb: 50
counter_cache_size_in_mb: 25

# Timeouts
read_request_timeout_in_ms: 5000
range_request_timeout_in_ms: 10000
write_request_timeout_in_ms: 2000
counter_write_request_timeout_in_ms: 5000