#!/bin/bash

echo "📋 AYUDA DEL SISTEMA E-COMMERCE CON REINFORCEMENT LEARNING"
echo "==========================================================="
echo ""
echo "🚀 COMANDOS PRINCIPALES:"
echo ""
echo "1️⃣  INICIALIZACIÓN COMPLETA:"
echo "   ./scripts/initialize_complete_system.sh"
echo "   └─ Inicia todo el sistema desde cero de manera automatizada"
echo ""
echo "2️⃣  VALIDACIÓN DEL SISTEMA:"
echo "   ./scripts/validate_system.sh"
echo "   └─ Verifica que todos los servicios estén funcionando correctamente"
echo ""
echo "3️⃣  COMANDOS DOCKER BÁSICOS:"
echo "   docker-compose up -d                    # Iniciar todos los servicios"
echo "   docker-compose down                     # Detener todos los servicios"
echo "   docker-compose down -v                  # Detener y eliminar volúmenes"
echo "   docker ps                               # Ver contenedores corriendo"
echo "   docker ps -a                            # Ver todos los contenedores"
echo ""
echo "4️⃣  SERVICIOS INDIVIDUALES:"
echo "   docker-compose up -d cassandra redis    # Solo servicios base"
echo "   docker-compose up -d rl-component       # Solo componente RL"
echo "   docker-compose up -d api                # Solo API backend"
echo ""
echo "5️⃣  LOGS Y DEPURACIÓN:"
echo "   docker logs ecommerce-rl                # Logs del sistema RL"
echo "   docker logs ecommerce-cassandra         # Logs de Cassandra"
echo "   docker logs ecommerce-api               # Logs del API"
echo "   docker logs ecommerce-ingesta           # Logs de ingesta"
echo "   docker-compose logs -f                  # Todos los logs en tiempo real"
echo ""
echo "📊 URLS DE SERVICIOS:"
echo ""
echo "🎯 DASHBOARDS PRINCIPALES:"
echo "   • RL Dashboard: http://localhost:8050"
echo "   • Frontend Principal: http://localhost:5174"
echo "   • API Backend: http://localhost:3003"
echo ""
echo "🔧 HERRAMIENTAS DE MONITOREO:"
echo "   • Flink Dashboard: http://localhost:8081"
echo "   • Kafka UI: http://localhost:8089"
echo "   • Cassandra Web: http://localhost:3005"
echo "   • Redis Commander: http://localhost:8088"
echo ""
echo "🔍 HEALTH CHECKS:"
echo "   • RL API Health: curl http://localhost:5000/health"
echo "   • Backend Health: curl http://localhost:3003/health"
echo "   • RL Metrics: curl http://localhost:5000/api/v1/rl/agent/state"
echo ""
echo "🛠️  COMANDOS DE MANTENIMIENTO:"
echo ""
echo "   # Reiniciar solo RL component"
echo "   docker-compose restart rl-component"
echo ""
echo "   # Regenerar datos de inventario"
echo "   docker-compose exec cassandra cqlsh -f /docker-entrypoint-initdb.d/05-inventory-rl-tables.cql"
echo ""
echo "   # Limpiar y reiniciar todo"
echo "   docker-compose down -v && ./scripts/initialize_complete_system.sh"
echo ""
echo "   # Ver métricas de Cassandra"
echo "   docker-compose exec cassandra cqlsh -e \"USE ecommerce_analytics; SELECT COUNT(*) FROM inventory_current;\""
echo ""
echo "📁 ESTRUCTURA DEL PROYECTO:"
echo ""
echo "   1.0_ingesta/         # Productor Kafka para datos transaccionales"
echo "   2.0_kafka/           # Configuración de Kafka"
echo "   3.0_flink/           # Jobs de procesamiento en tiempo real"
echo "   4.0_cassandra/       # Esquemas y configuración de base de datos"
echo "   5.0_redis/           # Configuración de cache"
echo "   6.0_app/             # Frontend y backend APIs"
echo "   7.0_rl/              # Sistema de Reinforcement Learning"
echo "   scripts/             # Scripts de automatización"
echo ""
echo "🔄 FLUJO TÍPICO DE TRABAJO:"
echo ""
echo "   1. Asegurar que Docker Desktop esté corriendo"
echo "   2. Ejecutar: ./scripts/initialize_complete_system.sh"
echo "   3. Esperar que termine la inicialización (5-10 minutos)"
echo "   4. Validar: ./scripts/validate_system.sh"
echo "   5. Acceder al RL Dashboard: http://localhost:8050"
echo ""
echo "❓ RESOLUCIÓN DE PROBLEMAS:"
echo ""
echo "   🔴 Si el dashboard muestra ceros:"
echo "      ./scripts/validate_system.sh      # Verificar estado"
echo "      docker logs ecommerce-rl          # Ver logs RL"
echo ""
echo "   🔴 Si Cassandra no inicia:"
echo "      docker-compose down -v"
echo "      docker system prune -f"
echo "      ./scripts/initialize_complete_system.sh"
echo ""
echo "   🔴 Si hay errores de puerto:"
echo "      netstat -an | findstr :8050        # Verificar puertos en uso"
echo "      docker-compose down               # Liberar puertos"
echo ""
echo "📞 SOPORTE:"
echo "   - Revisar logs con docker logs [container_name]"
echo "   - Verificar puertos con netstat o docker ps"
echo "   - Reinicializar con el script completo"
echo ""
echo "🎉 ¡El sistema está diseñado para funcionar automáticamente después de ejecutar initialize_complete_system.sh!" 