jobmanager.rpc.address: jobmanager
jobmanager.rpc.port: 6123
jobmanager.bind-host: 0.0.0.0
taskmanager.bind-host: 0.0.0.0
rest.bind-address: 0.0.0.0

# Configuración de Akka
akka.ask.timeout: 300s
akka.lookup.timeout: 300s
akka.framesize: 419430400b
akka.throughput: 15
akka.log-config-on-start: off
akka.jvm-exit-on-fatal-error: true
akka.remote.startup-timeout: 300s

# Slots por TaskManager
taskmanager.numberOfTaskSlots: 2

# Paralelismo por defecto
parallelism.default: 2

# Backend de estado y checkpoints
state.backend: filesystem
state.checkpoints.dir: file:///opt/flink/checkpoints
state.savepoints.dir: file:///opt/flink/savepoints

# Estrategia de reinicio
restart-strategy: fixed-delay
restart-strategy.fixed-delay.attempts: 3
restart-strategy.fixed-delay.delay: 10 s

# Python
python.client.executable: /usr/bin/python3

# Memoria explícita para evitar error
jobmanager.memory.process.size: 1024m
taskmanager.memory.process.size: 1024m

# Configuración de red
blob.server.port: 6124
query.server.port: 6125
